context.properties = {
    default.clock.rate = 96000
    clock.force-rate = 96000
    default.clock.allowed-rates = [ 96000 ]
    default.clock.quantum = 1024
    default.clock.min-quantum = 64
    default.clock.max-quantum = 2048
    resample.quality = 8
    audio.format = S32LE
}
