#клавиша-модификатор
$mainMod = SUPER
#хоткеи
bind = $mainMod,return ,exec, $terminal
bind = $mainMod,c,exec,$vim
bind = $mainMod , x, killactive, 
bind = $mainMod,w,exec,$browser
bind = $mainMod SHIFT,w,exec, killall waybar||waybar
bind = $mainMod,g,exec,wpctl set-volume @DEFAULT_SINK@ 5%+ 
bind = $mainMod,f,exec,wpctl set-volume @DEFAULT_SINK@ 5%-
bind = $mainMod,Q,exit, 
bind = $mainMod,E,exec, $fileManager
bind = $mainMod,V,togglefloating, 
bind = $mainMod,S, exec,$steam
bind = $mainMod,P,exec,grim -g "$(slurp)"
bind = $mainMod,T,exec ,$browser "web.telegram.org"
bind = $mainMod,M,exec,java -jar TLauncher.jar
bind = $mainMod SHIFT,s,exec,skypeforlinux
bind = $mainMod,O,exec,libreoffice
bind = $mainMod SHIFT,O,exec,obsidian
bind = $mainMod SHIFT,V,exec,vlc
bind = $mainMod SHIFT,K,exec,krita
bind = $mainMod SHIFT, x,exec,wlogout
bind = $mainMod SHIFT,p,exec,wl-color-picker
#переключение между окнами в рабочем пространстве
bind = $mainMod,h,movefocus, l
bind = $mainMod,l, movefocus, r
bind = $mainMod,k, movefocus, u
bind = $mainMod,j, movefocus, d
#переключение рабочих пространств
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
#перемещение активного окна на заданную рабочую область
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
#переключение активных рабочих облостей 
bind = $mainMod, tab, workspace, e+1
bind = $mainMod SHIFT, tab, workspace, e-1
