#alacritty
windowrule = workspace 1,Alacritty
windowrule = opacity 0.9,Alacritty
#zen-browser
windowrule = workspace 2,zen
windowrule = opacity 0.9,zen
#steam
windowrule = workspace 3,steam
windowrule = tile,steam
windowrule = opacity 0.9,steam
#pavucontrol
windowrule = float,pavucontrol
windowrule = move 943 433,pavucontrol
windowrule = pin,pavucontrol
windowrule = size 290 236,pavucontrol
#Tlauncher
windowrule = workspace 3,TLauncher
#Minecraft*
windowrule = workspace 3,Minecraft*
windowrule = tile,Minecraft*
#Skypeforlinux
windowrule = workspace 4,Skype
#libreoffice-stil
windowrule = workspace 5,libreoffice
#obsidian
windowrule = workspace 6,obsidian
#vlc
windowrule = workspace 7,vlc
#krita
windowrule = workspace 8,krita
