source=~/.config/hypr/modules/animations.conf
source=~/.config/hypr/modules/autostart.conf
source=~/.config/hypr/modules/declorations.conf
source=~/.config/hypr/modules/decorations.conf
source=~/.config/hypr/modules/device.conf
source=~/.config/hypr/modules/env.conf
source=~/.config/hypr/modules/input.conf
source=~/.config/hypr/modules/keybinds.conf
source=~/.config/hypr/modules/layout_dwindle.conf
source=~/.config/hypr/modules/layout_master.conf
source=~/.config/hypr/modules/layout_monocle.conf
source=~/.config/hypr/modules/misc.conf
source=~/.config/hypr/modules/settings.conf
source=~/.config/hypr/modules/windowrule.conf
source=~/.config/hypr/modules/workspaces.conf
source=~/.config/hypr/modules/xwayland.conf
