#alacrity
windowrule = opacity 0.9,Alacritty
windowrule = workspace 1,Alacritty
#zen-browser
windowrule = workspace 2,firefox
windowrule = opacity 0.9,firefox
windowrulev2 = opacity 1,title:.*Яндекс.*
windowrulev2 = float,title:Library
windowrulev2 = opacity 1,title:Library
windowrulev2 = center,title:Library
#steam
windowrule = workspace 3,steam
windowrule = tile,steam
windowrule = opacity 0.9,steam
#pavucontrol
windowrule = float,org.pulseaudio.pavucontrol
windowrule = move 928 433,org.pulseaudio.pavucontrol
windowrule = size 339 246,org.pulseaudio.pavucontrol
windowrule = pin,org.pulseaudio.pavucontrol
#Tlauncher
windowrule = workspace 3,org-tlauncher-tlauncher-rmo-TLauncher
#Minecraft*
windowrulev2 = workspace 3,title:.*Minecraft*.*
#Skypeforlinux
windowrule = workspace 4,Skype
windowrulev2 = center,title:.*Open Files.*
windowrulev2 = size 640 360,title:.*Open Files.*
#libreoffice-stil
windowrule = workspace 5,libreoffice-startcenter
windowrulev2 = center,title:.*Save.*
windowrulev2 = size 640 360,title:.*Save.*
#obsidian
windowrule = workspace 6,obsidian
windowrule = center,obsidian
windowrulev2 = center,title:Location
#vlc
windowrule = workspace 7,vlc
windowrulev2 = center,title:.*Select.*
windowrulev2 = size 640 360,title:.*Select.*
windowrulev2 = center,title:.*Simple Preferences.*
windowrulev2 = size 640 360,title:.*Simple Preferences.*
#krita
windowrule = workspace 8,krita
windowrule = center,krita
windowrulev2 = center,title:Saving As — Krita
windowrulev2 = size 640 360,title:Saving As — Krita
windowrulev2 = center,title:Create new document — Krita
windowrulev2 = size 640 360,title:Create new document — Krita
windowrulev2 = center,title:.*Open Images.*
windowrulev2 = size 640 360,title:.*Open Images.*

#no border
windowrulev2 = noborder,onworkspace:
