hl.on("hyprland.start",function ()
    hl.exec_cmd("quickshell")
    hl.exec_cmd("syshud")
    hl.exec_cmd("snappy-switcher --daemon")
    -- hl.exec_cmd("pwsp-daemon")
    hl.exec_cmd("Xwayland")
end)
