#Мониторы
$main_monitor = HDMI-A-1
$second_monitor = eDP-1
#Программы
$term = foot 
$filemanager = $term --app-id=filemanager -e yazi
$menu = --class=menu hyprlauncher
$minecraft=prismlauncher 
$nvim = $term -e nvim
$browser = MOZ_ENABLE_WAYLAND=1 zen-browser 
$youtube = $browser  youtube.com
$discord = flatpak run net.russcord.app
$proton = portproton
$onlyoffice = onlyoffice-desktopeditors
$roblox = flatpak run org.vinegarhq.Sober
$cursor = hyprctl setcursor "WinSur-dark-cursors" 30
$gotop = $term --app-id=gotop -e gotop
$ff = $term --app-id=ff -e zsh  -c "fastfetch;zsh"
$clock = $term --app-id=tty_clock -e tty-clock
$zapret = $term --app-id=zapret -e zapret
#Клавиша-модификатор
$mainMod = SUPER
