local dec = require("modules.declorations")
hl.bind("SUPER + Return",hl.dsp.exec_cmd(dec.TERMINAL))
hl.bind("SUPER + F", hl.dsp.exec_cmd(dec.FASTFETCH))
hl.bind("SUPER + Escape", hl.dsp.exec_cmd(dec.TOP))
hl.bind("SUPER + D",hl.dsp.exec_cmd(dec.DISCORD))
hl.bind("SUPER + R",hl.dsp.exec_cmd(dec.RUSCORD))
hl.bind("SUPER + SHIFT + R",hl.dsp.exec_cmd(dec.ROBLOX))
hl.bind("SUPER + E", hl.dsp.exec_cmd(dec.EXPLORER))
hl.bind("SUPER + S",hl.dsp.exec_cmd("steam"))
hl.bind("SUPER + W", hl.dsp.exec_cmd(dec.BROWSER))
hl.bind("SUPER + X", hl.dsp.window.close())
hl.bind("SUPER + T",hl.dsp.exec_cmd("Telegram"))
hl.bind("SUPER + SHIFT + S",hl.dsp.exec_cmd(dec.SOUNDPAD))
hl.bind("CTRL + ALT + DELETE", hl.dsp.exec_cmd("wlogout"))
hl.bind("SUPER + C",hl.dsp.exec_cmd(dec.EDITOR))
hl.bind("SUPER + SHIFT + C",hl.dsp.exec_cmd(dec.COLORPICKER))
hl.bind("SUPER + P",hl.dsp.exec_cmd("hyprshot -m output"))
hl.bind("SUPER + SHIFT + P",hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind("SUPER + M",hl.dsp.exec_cmd("prismlauncher"))
hl.bind("SUPER + Q",hl.dsp.exec_cmd(dec.EXIT))
hl.bind("SUPER + SHIFT + O",hl.dsp.exec_cmd("obsidian"))
hl.bind("SUPER + O",hl.dsp.exec_cmd("onlyoffice-desktopeditors"))
hl.bind("SUPER + Y",hl.dsp.exec_cmd(dec.YOUTUBE))
hl.bind("ALT + Tab", hl.dsp.exec_cmd(dec.SWITCHER))
hl.bind("SUPER + K",hl.dsp.exec_cmd("krita"))
hl.bind("SUPER + H",hl.dsp.exec_cmd("happ"))
hl.bind("SUPER + Z",hl.dsp.exec_cmd(dec.ZAPRET))
--Переключение окон в monocle layout
hl.bind("SUPER + Right",hl.dsp.window.cycle_next({ tiled = true }))
-- Переключение workspace
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = "2" }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = "3" }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = "4" }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = "5" }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = "6" }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = "7" }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = "8" }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = "9" }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "10" }))
--Перенос окна на workspace
hl.bind("SUPER + SHIFT + 1",hl.dsp.window.move({workspace = "1"}))
hl.bind("SUPER + SHIFT + 2",hl.dsp.window.move({workspace = "2"}))
hl.bind("SUPER + SHIFT + 3",hl.dsp.window.move({workspace = "3"}))
hl.bind("SUPER + SHIFT + 4",hl.dsp.window.move({workspace = "4"}))
hl.bind("SUPER + SHIFT + 5",hl.dsp.window.move({workspace = "5"}))
hl.bind("SUPER + SHIFT + 6",hl.dsp.window.move({workspace = "6"}))
hl.bind("SUPER + SHIFT + 7",hl.dsp.window.move({workspace = "7"}))
hl.bind("SUPER + SHIFT + 8",hl.dsp.window.move({workspace = "8"}))
hl.bind("SUPER + SHIFT + 9",hl.dsp.window.move({workspace = "9"}))
--Управление громкостью
hl.bind("XF86AudioRaiseVolume",hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_SINK@ 5%+"))
hl.bind("XF86AudioLowerVolume",hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_SINK@ 5%-"))
--Управление воспроизведением
hl.bind("XF86AudioPlay",hl.dsp.exec_cmd("playerctl play-pause"))

