monitor = $main_monitor,1920x1080@165,0x0,1
workspace = 1, monitor:$main_monitor,layout:dwindle
workspace = 2, monitor:$main_monitor
workspace = 3, monitor:$main_monitor,layout:monocle,border:false
workspace = 4, monitor:$second_monitor,layout:monocle
workspace = 5, monitor:$second_monitor,layout:monocle,rounding=0,border:true
workspace = 6, monitor:$main_monitor
workspace = 7, monitor:$main_monitor
workspace = 8, monitor:$main_monitor,layout:monocle
workspace = 9, monitor:$second_monitor
workspace = 10,monitor:$second_monitor,gapsout:0,gapsin:0

