local dec = require("modules.declorations")
hl.workspace_rule({workspace = "1",monitor = dec.MAIN_MONITOR})
hl.workspace_rule({workspace = "2",monitor = dec.MAIN_MONITOR})
hl.workspace_rule({workspace = "3",monitor = dec.MAIN_MONITOR,layout = "monocle"})
hl.workspace_rule({workspace = "4",monitor = dec.SECOND_MONITOR,layout = "monocle"})
hl.workspace_rule({workspace = "5",monitor = dec.SECOND_MONITOR})
hl.workspace_rule({workspace = "6",monitor = dec.MAIN_MONITOR})
hl.workspace_rule({workspace = "7",monitor = dec.MAIN_MONITOR})
hl.workspace_rule({workspace = "8",monitor = dec.MAIN_MONITOR})
hl.workspace_rule({workspace = "9",monitor = dec.SECOND_MONITOR,layout = "monocle"})
hl.workspace_rule({workspace = "10",monitor = dec.SECOND_MONITOR,gaps_out = 0})
